;;; iceberg-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from iceberg-theme.el

(autoload 'iceberg-theme-create-theme-file "iceberg-theme" "\
Create iceberg-theme color theme using solarized API.

Solarized pallete.

brightest                                   darkest
base03 base02 base01 base00 base0 base1 base2 base3

yellow orange red magenta violet blue cyan green")
(define-obsolete-function-alias 'iceberg-theme-create-theme 'iceberg-theme-create-theme-file "28")

;;; End of scraped data

(provide 'iceberg-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; iceberg-theme-autoloads.el ends here
