;;; flexoki-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flexoki-themes.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "flexoki-themes" '("flexoki-themes-"))


;;; Generated autoloads from flexoki-themes-dark-theme.el

(register-definition-prefixes "flexoki-themes-dark-theme" '("flexoki-themes-dark"))


;;; Generated autoloads from flexoki-themes-light-theme.el

(register-definition-prefixes "flexoki-themes-light-theme" '("flexoki-themes-light"))

;;; End of scraped data

(provide 'flexoki-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flexoki-themes-autoloads.el ends here
