# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x11111bff
rootcolor = 0x1e1e2eff
bordercolor = 0x6c7086ff
dropcolor = 0x74c7ec80
splitcolor = 0x89dcebff
focuscolor = 0x74c7ecff
maximizescreencolor = 0x89b4faff
urgentcolor = 0xf38ba8ff
scratchpadcolor = 0x89dcebff
globalcolor = 0x0875a6ff
overlaycolor = 0x004fd1ff
jump_label_decorate_fg_color = 0xcdd6f4ff
jump_label_decorate_bg_color = 0x3a3b50ff
jump_label_decorate_focus_fg_color = 0x1e1e2eff
jump_label_decorate_focus_bg_color = 0x74c7ecff
jump_label_decorate_border_color = 0x6c7086ff
group_bar_decorate_fg_color = 0xcdd6f4ff
group_bar_decorate_bg_color = 0x3a3b50ff
group_bar_decorate_focus_fg_color = 0x1e1e2eff
group_bar_decorate_focus_bg_color = 0x74c7ecff
group_bar_decorate_border_color = 0x6c7086ff
