# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0xfdf5e2ff
bordercolor = 0x879091ff
dropcolor = 0x29a29880
splitcolor = 0xb28500ff
focuscolor = 0x29a298ff
maximizescreencolor = 0xdb302dff
urgentcolor = 0xdb302dff
scratchpadcolor = 0xb28500ff
globalcolor = 0xa5d8d4ff
overlaycolor = 0xecc6c5ff
jump_label_decorate_fg_color = 0x576d74ff
jump_label_decorate_bg_color = 0xe7dfc5ff
jump_label_decorate_focus_fg_color = 0x001419ff
jump_label_decorate_focus_bg_color = 0x29a298ff
jump_label_decorate_border_color = 0x879091ff
group_bar_decorate_fg_color = 0x576d74ff
group_bar_decorate_bg_color = 0xe7dfc5ff
group_bar_decorate_focus_fg_color = 0x001419ff
group_bar_decorate_focus_bg_color = 0x29a298ff
group_bar_decorate_border_color = 0x879091ff
