# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x282a36ff
rootcolor = 0x282a36ff
bordercolor = 0x6d728bff
dropcolor = 0xbd93f980
splitcolor = 0x8be9fdff
focuscolor = 0xbd93f9ff
maximizescreencolor = 0xff79c6ff
urgentcolor = 0xff5555ff
scratchpadcolor = 0x8be9fdff
globalcolor = 0x5a00d9ff
overlaycolor = 0xc60071ff
jump_label_decorate_fg_color = 0xf8f8f2ff
jump_label_decorate_bg_color = 0x4d5066ff
jump_label_decorate_focus_fg_color = 0x282a36ff
jump_label_decorate_focus_bg_color = 0xbd93f9ff
jump_label_decorate_border_color = 0x6d728bff
group_bar_decorate_fg_color = 0xf8f8f2ff
group_bar_decorate_bg_color = 0x4d5066ff
group_bar_decorate_focus_fg_color = 0x282a36ff
group_bar_decorate_focus_bg_color = 0xbd93f9ff
group_bar_decorate_border_color = 0x6d728bff
