;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua-paste
	indent-for-tab-command
	keyboard-escape-quit
	org-cycle
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	ignore
	mouse-buffer-menu
	mouse-set-region
	))
