;;; markdown-mermaid-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from markdown-mermaid.el

(autoload 'markdown-mermaid-preview "markdown-mermaid" "\
Compile and preview the Mermaid block under cursor." t)
(register-definition-prefixes "markdown-mermaid" '("markdown-mermaid-"))

;;; End of scraped data

(provide 'markdown-mermaid-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; markdown-mermaid-autoloads.el ends here
