;;; app-monochrome-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from app-monochrome-themes.el

(add-to-list 'custom-theme-load-path (if load-file-name (file-name-directory load-file-name) default-directory))


;;; Generated autoloads from app-monochrome-themes-dark-theme-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "app-monochrome-themes-dark-theme-theme" '("app-monochrome-themes-dark-theme"))


;;; Generated autoloads from app-monochrome-themes-light-theme-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "app-monochrome-themes-light-theme-theme" '("app-monochrome-themes-light-theme"))

;;; End of scraped data

(provide 'app-monochrome-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; app-monochrome-themes-autoloads.el ends here
