#!/usr/bin/env bash
picom -b &
skippy-xd --start-daemon &
# Set desktop identifier
export XDG_CURRENT_DESKTOP=ICEWM

# Import display variables into user session
systemctl --user import-environment DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP
