theme = "noctalia"
[editor]
line-number = "relative"
auto-format = true
[editor.file-picker]
hidden = true
[editor.whitespace.render]
space = "none"
# tab = "all"
tab = "none"
newline = "none"
[editor.indent-guides]
render = true
[keys.normal]
space.s = [":indent-style t", ":w"]
i = [":indent-style t", "collapse_selection", "insert_mode"]
a = [":indent-style t", "collapse_selection", "insert_mode"]
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
[editor.whitespace.characters]
# tabpad ="·"
# tab ="·"
