theme = "noctalia"
[editor]
line-number = "relative"
auto-format = false
[editor.file-picker]
hidden = true
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
[keys.normal]
space.s = [":set autoformat false", ":w"]
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
