theme = "gruvbox"
[editor]
line-number = "relative"
auto-format = false
[editor.file-picker]
hidden = true
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
[keys.normal]
space.s = [":indent-style 4", ":w"]
i = [":indent-style 4", "collapse_selection", "insert_mode"]
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
