[language-server.ccls]
command = "ccls"

[[language]]
indent = { tab-width = 4, unit = " " }
name = "c"
language-servers = ["ccls"]

[language-server.superhtml]
command = "superhtml"

[[language]]
indent = { tab-width = 4, unit = " " }
name = "html"
language-servers = ["superhtml"]

[language-server.pyright]
command = "pyright"

[[language]]
name = "python"
indent = { tab-width = 4, unit = " " }
language-servers = [ "pyright" ]


[language-server.nixd]
command = "nixd"

[[language]]
name = "nix"
indent = { tab-width = 4, unit = " " }
language-servers = [ "nixd" ]

[[language]]
name = "text"
indent = { tab-width = 4, unit = " " }
