# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
	config,
	lib,
	pkgs,
	modulesPath,
	...
}:

{
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];

	boot.initrd.availableKernelModules = [
		"xhci_pci"
		"ahci"
		"nvme"
		"usbhid"
		"usb_storage"
		"sd_mod"
	];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ ];

	fileSystems."/mnt/mirror" = {
		device = "/dev/disk/by-uuid/a7e8b3e3-71bc-4dbb-9b71-7fa4ec572e8e";
		fsType = "ext4";
		options = [
			"nofail"
			"x-systemd.automount"
		];
	};

	fileSystems."/" = {
		device = "/dev/disk/by-uuid/7584a5dc-94dd-4cf8-ae21-f936ba16b8b6";
		fsType = "ext4";
	};

	fileSystems."/boot/efi" = {
		device = "/dev/disk/by-uuid/33E5-49A5";
		fsType = "vfat";
		options = [
			"fmask=0077"
			"dmask=0077"
		];
	};

	swapDevices = [
		{ device = "/dev/disk/by-uuid/cc895d7c-a079-491b-af6a-6e002b7e65ce"; }
	];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
